
  - name: Add Elasticsearch APT repository key
    apt_key:
      url: https://packages.elastic.co/GPG-KEY-elasticsearch
    async: 3600
    poll: 0

  - name: Add Elasticsearch APT repository
    apt_repository:
      repo: "deb http://packages.elastic.co/elasticsearch/1.7/debian stable main"
    async: 3600
    poll: 0

  - name: Add Kibana APT repository
    apt_repository:
      repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    async: 3600
    poll: 0

  - name: Add Logstash APT repository
    apt_repository:
      repo: "deb http://packages.elasticsearch.org/logstash/1.5/debian stable main"
    async: 3600
    poll: 0

  - name: Install Elasticsearch on Ubuntu
    apt:
      name: elasticsearch
      state: present
    async: 3600
    poll: 0

  - name: Install Kibana on Ubuntu
    apt:
      name: kibana
      state: present
    async: 3600
    poll: 0

  - name: Install Logstash on Ubuntu
    apt:
      name: logstash
      state: present
    async: 3600
    poll: 0

  - name: Enable and Start Elasticsearch, Kibana, and Logstash
    systemd:
      name: "{{ item }}"
      enabled: yes
      state: started
    loop:
      - elasticsearch
      - kibana
      - logstash
    async: 3600
    poll: 0


